### ISSUE TITLE
iscroll-pull.js / iscroll-pull.css not include in the repo

### ISSUE THREAD

**Issue by vbarrier** [watusi/jquery-mobile-iscrollview#10]
As shown inside demo/pull-down.html, iscroll-pull.js / iscroll-pull.css should be in the repo.

**Comment by jtara** [comment]
Whoops! Looks like pulldown.html leaked into the repo prematurely! It's meant to replace "baz.html" in the demo. Nothing links to this page yet. I'll be updating shortly.

**Comment by fishernet** [comment]
jtara, any idea when you will be updating the pull to refresh sample with iscroll-pull.js?

**Comment by jtara** [comment]
Sorry, I am battling some regressions after an extensive performance update. I'd planned on 1.2 being mainly the pull-down pull-up, but then I realized that it had some serious performance issues that were impeding my own work and they had to be fixed. I'm happy to say that the performance has been improved tremendously and the pull-down/pull-up work perfectly. (The original iscroll example has some serious issues with pull-up.) I wound-up putting the pull-down/pull-up right in the widget, so you only need to add a bit of markup and a callback to perform the fetch/insert. But some bugs inevitably crept-in. I do expect the 1.2 update within the next day or two.

**Comment by mikestecker** [comment]
I've been watching this project and am eager to get my hands on your update. Any more updates on when you expect 1.2 to be ready?

**Comment by jtara** [comment]
1.2 now has pull-up/pull-down support internally.
