### ISSUE TITLE
A bug while using iscrollview on iPad 2 safari 5

### ISSUE THREAD

**Issue by llin96** [watusi/jquery-mobile-iscrollview#11]
I found a bug while using iscrollview on iPad 2 safari 5.

I am using iscrollview with jquery switch control inside (in listview), run the page on iPad 2 safari 5, when I touch the circle image to switch value, the browser then redirect me to location "#". for example, when I am in http://domain/index.html#bar, after I touch the switch button circle image, the browser location goes to http://domain/index.html#.

I am not sure if it's caused by safari 5 or iscrollview or iSroll 4:

If I run the page on PC with safari 5, everything works correct.
If I run the page on iPad2 with safari 5 but remove iscrollview and iScroll 4, everything works correct, too

Using firebug to check DOM elements, I find jquery mobile generate '&lt;a href="#"...&gt;..&lt;/a&gt;' child element for a circle button. I guess something caused by iscrollview (or iScroll 4) which redirect me to "#" while touch the circle image.

Any help on this would be appreciate!

**Comment by jtara** [comment]
Confirmed, and still present in 1.2. It's OK as long as you click somewhere else other than on the circle. Clicking on the circle will fire the redirect.

I think, though, this may be a jQuery Mobile usage issue. It seems to be doing exactly what it should! That is, the switch control does indeed generate the `<a href="#">`, and so the browser is doing just what one would expect... I don't know why the switch control does this, and the jQuery Mobile documentation isn't helpful. :( I imagine that the intent is that the flip switch can be used as _either_ a form element or as a button, but they haven't documented this usage.

**Comment by jtara** [comment]
Please test with 1.2 and report your results.

Thanks.

**Comment by jtara** [comment]
Unable to reproduce using 1.2pre1. Please test and let me know if you still see this issue.
