### ISSUE TITLE
Iscrollview on second page doesn't scroll on second link

### ISSUE THREAD

**Issue by play75010** [watusi/jquery-mobile-iscrollview#110]
Hello.

I've got a main list view which scrolls perfectly.

Each list item links to the same page (which is also a list view).

On the first time I click on any of the list items, the landing page scrolls fine.

On the second and subsequent clicks, the landing page is frozen. 

I've tried with JQM-iscrollview 1.3.1 and 1.3.2

Any idea ?

**Comment by jtara** [comment]
Can you provide a complete example?

**Comment by play75010** [comment]
I cannot provide my current app since it is going to the store tomorrow but I'll definitively provide an example in a few days.

**Comment by jtara** [comment]
If you can provide an example, I will re-open the Issue.
