### ISSUE TITLE
 is it possible to upgrade to  support iscroll 4.2.5 or 5.0? 

### ISSUE THREAD

**Issue by cagev** [watusi/jquery-mobile-iscrollview#115]
it's very slow with 4.2.5 and it seems there's no where to download iscroll 4.2 also.

**Comment by play75010** [comment]
You can find 4.2 here : https://github.com/watusi/jquery-mobile-iscrollview/tree/master/demo/source/javascripts

**Comment by cagev** [comment]
thanks
