### ISSUE TITLE
iscrollview with JQM and Windows 8 Javascript

### ISSUE THREAD

**Issue by n7167113** [watusi/jquery-mobile-iscrollview#122]
I was just wondering if this was possible to be used with JQM on Windows 8 Javascript app?

I don't really like the development for Windows 8 Javascript app but I wanted to know if there's a way to work around this because I like this library.

The current problem I'm having at the moment is that I get 'removeChild' is undefined or null referenced. This happens when I make/remove dynamic contents declared as data-iscroll.

Without going into too much details on code; would you be able to tell me if this has been tested on Windows 8 and whether or not similar issues has occurred and how to fix if possible.

**Comment by jtara** [comment]
No interest in supporting this, sorry.

I'm planning on a new widget for iScroll5. If somebody else wants to contribute Windows 8 support once I start that effort, happy to accept the assistance.

Primary emphasis will be for iOS and Android, and webkit and Mozilla-based desktop browsers.
