### ISSUE TITLE
Page not scrolling while using data-iscroll

### ISSUE THREAD

**Issue by Remya-Thomas** [watusi/jquery-mobile-iscrollview#136]
We are developing a screen which is used for both for iPhone and iPad. In iPad for the same screen, we are implementing pull to refresh. But in iPhone, this screen doesn't have pull to refresh. Due to this functionality in iPad, iPhone screen is becoming non-scrollable. This is due to the data-iscroll. Is there any workaround for this ?

Thanks in advance

**Comment by jtara** [comment]
Will re-open if you can provide more details or can demonstrate this with the demo.
