### ISSUE TITLE
scrollbar disappears when content is banner image plus list buttons

### ISSUE THREAD

**Issue by putztzu** [watusi/jquery-mobile-iscrollview#14]
The original content without any scrolling plugin can be viewed as a reference as how the content should look
http://3horn.us/sdiego/index.html

When all the content on the page is scrollable (both banner image plus list), you will see that the scrollbar at the right of the screen has disappeared and the display is no longer viewable, and in fact the screen is not scrollable at all (eg using swipe even if the scrollbar is not available).
http://3horn.us/sdiego/index2.html

I will submit the issues related to scrolling only the list content in a separate bug.

Tested on Android 2.3.4 and desktop Chrome, believe this behavior would be the same on other devices as well.

Great stuff if this works.

Thx,
TS

**Comment by jtara** [comment]
iScroll scrolls only the first child of the wrapper. In this case, that first child is your banner. So, it's scrolling the banner.

If you want to scroll the banner + listview, put a div around the two.

In 1.2, the widget will create this protective div for you automatically.

**Comment by putztzu** [comment]
Thx jtara,
So, currently the scrollview attribute is already applied to a "content" div surrounding both the banner and listview objects.

Are you suggesting that <another> div that does not include the scrollview attribute be placed around these objects?

Thx,
TS

**Comment by jtara** [comment]
Yes, because iScroll only scrolls the first child of the wrapper. The wrapper is the element that has the data-iscroll attribute. If you want to scroll multiple elements, you have to group them under a div (or other element). 

This will change in 1.2, since the way iScroll does this doesn't make much sense to me. Now the widget will just create the grouping div for you.

**Comment by jtara** [comment]
1.2 now scrolls all children of the wrapper.
