### ISSUE TITLE
IScroll 5 support

### ISSUE THREAD

**Issue by jeerbl** [watusi/jquery-mobile-iscrollview#140]
Hi,
Will the support for iScroll 5 be available soon?

Jérôme

**Comment by gabaum10** [comment]
+1 to iScroll5 support.  Much improved over iScroll4 and would be beneficial to this project.

**Comment by frankie-loves-jesus** [comment]
Guys see https://github.com/watusi/jquery-mobile-iscrollview/issues/118.

**Comment by jtara** [comment]
This will happen eventually, but it will be a new project. It will work with jQuery and jQuery UI as well then.

Sorry, no ETA. But I am about to use the beginnings of that plugin in a project of my own.
