### ISSUE TITLE
Searching a JS for small freelancer work

### ISSUE THREAD

**Issue by buildpress** [watusi/jquery-mobile-iscrollview#145]
Hello,

I know it's not a job board but i hopefully get the credits from the repo owner to ask my question here like this for once......

I have a phonegap app (angular JS with offcourse iscroll :-) ) where i need someone to code specifc JS parts in the backend and template view files.

I had great programmers from the Ukraine but because of the war up there i lost contact. I tried several job websites but it took so much time and i didn't find anyone with time or knowledge of the Phonegap backbone structure i have. My app is running on a JSON api output.

So, is there someone who can help me out with JS on a freelancer base?
Thnx

Jasper

**Comment by frankie-loves-jesus** [comment]
No. Please close this issue, it doesn't belong here.
