### ISSUE TITLE
Support for IE on Windows Surface RT

### ISSUE THREAD

**Issue by n7167113** [watusi/jquery-mobile-iscrollview#150]
I've tested this library on my laptop with most of the main browsers such as Chrome, Firefox, Safari and Internet Explorer and they all work fine.

It's just when I tried testing this on a Windows Surface RT tablet that it doesn't work. I used the Internet Explorer app on the RT but when tried scrolling nothing happens. There's not bouncing to indicate that it registers that swipe event, no movement no nothing. 

Is this just an unsupported area of the library or is this an error?

**Comment by frankie-loves-jesus** [comment]
## Reduced test case required

Please see [CSS Tricks - Reduced Test Cases](http://css-tricks.com/reduced-test-cases/) on why they _"are the absolute, ... number one way to troubleshoot bugs."_
- A reduced test case is an isolated example that demonstrates the bug or issue.
- It contains the bare minimum HTML, CSS, and JavaScript required to demonstrate the bug. No extra functionality or styling.
- A link to your site is not a reduced test case.

**Comment by frankie-loves-jesus** [comment]
Actually though, this whole library is obsolete:

https://github.com/watusi/jquery-mobile-iscrollview/issues/118

**Comment by n7167113** [comment]
I've read your article about reducing everything to its simplicity and should probably tell you that it's currently at the most basics.

I have an empty page with nothing else on it except for a dummy list that is very long. The list is inside a container div with attribute "data-iscroll". (Not sure how much simpler it can get).

I'm running this site on an Apache server locally and I've just been testing on the range of support for this library and it works on all the browsers when testing on my Macbook (as mentioned before).

It's just when testing on my Windows Surface RT that it does not work completely. But when testing again just now, I did see that the listview is bouncing so maybe before it was just my device. The listview is bouncing but it's still not scrolling. I should also point out that I've also tested this on my Samsung phone, tablet as well as my iPhone and iPad.

I'm using JQM 1.4.3 and iscrollview (can't remember what release though) which you said was obsolete (but at the moment should still be usable right?)

I tried creating a JS fiddle for this but I can't get external libraries to work so I can only give you the current code.

At the root of my project, I have my index page and all the required libraries (i.e. jquery, jquery mobile and iscrollview plus all the themes for jquery mobile etc).

The body tag of my index page is simply:

```
<body>
     <div data-role='page'>
          <div data-role='content'>
               <div class='myScroller' data-iscroll>
                    <ul data-role='listview'>
                         ....
                         <li>alot of this copied and pasted</li>
                         ....
                   </ul>
              </div><!-- myScroller --->
          </div><!-- content -->    
     </div><!-- page -->
</body>
```

And that's it. The only problem that I can see that might cause this issue is the fact the you said iscrollview is obsolete but was wondering if that's the only case or is it the fact that it just doesn't support it at all?

**Comment by n7167113** [comment]
Ok so I managed to setup a JS Fiddle to demo the issue now. I've tested this again on the Windows Surface RT and still the same issue.

http://jsfiddle.net/n7167113/4r40qw1c/1/

**Comment by frankie-loves-jesus** [comment]
Yes, iScrollView is obsolete as you no longer need it to get iScroll working with jQuery Mobile. Please try with my iScroll 5 fiddle at #118 and if the problem still persists, report it to the main iScroll repo.

**Comment by n7167113** [comment]
It seems that the iscroll used by the iscrollview library on this git is out of date. I tried another test using the latest (or at least, a newer version of iScroll) found at https://github.com/cubiq/iscroll and it does seem to work.

The example is just a straight copy and paste from their demo and it does work on the Windows Surface RT plus all the other browser I've tested on. http://jsfiddle.net/n7167113/4134z9ra/1/

However, to get that to work, I had to setup all that CSS styling and run that script to create the scroller and basically to much effort in comparison with iscrollview.

Are there any plans for iscrollview to use the latest version of iScroll?

**Comment by n7167113** [comment]
Hi frankie,

I posted my last update just a little bit later than you. I went through the posted link you said and found this fiddle to be the most appropriate answer for my problem so far.

http://jsfiddle.net/frank_o/DWKNw/9/

I think I can leave this at that as it's the best solution so far which works fine.

**Comment by jtara** [comment]
IE is not, never has been, and will not be supported. Sorry.

I'm working on a NEW plugin that will wrap iScroll5. It's meant for jQuery, jQuery UI, and jQuery Mobile. The current jquery.mobile.iscrollview will not be updated. It will support those browsers that are supported by iScroll5.

For simple cases, you can certainly use iScroll4 or iScroll5 without any wrapper. This plugin was meant as an easy way of incorporating iScroll into a JQM project, without a lot of fiddling.
