### ISSUE TITLE
Weird height issue

### ISSUE THREAD

**Issue by mal3k** [watusi/jquery-mobile-iscrollview#151]
Hi,

I am loading data asynchronously into the scroller, the first time the scroller is loaded, I call refresh but when I scroll to the bottom, I can see the content is not completely loaded and the scroller don't allow me to scroll beyond, but when I manually pull to refresh, the scroller height is adjusted correctly and I can then scroll to the complete content of the scroller. (I use only the pull down to refresh).

Is this probably a bug?

**Comment by jtara** [comment]
You need to call iScrollView's `refresh()` method or else `trigger('updatelayout')` on any element inside the scroller after changing any content.
