### ISSUE TITLE
Issue with Cordova App after deploying to IOS 9

### ISSUE THREAD

**Issue by ecnopdev** [watusi/jquery-mobile-iscrollview#155]
Hi,

I have a cordova application that makes use of this great tool and it seems to work well on both android and ios platforms not until I upgraded to IOS9 then I encountered this issue.

ISSUE: When calling the pull events, instead of applying that "snap-back" on the list, it is doing to the wrapper and effectively dragging up/down the whole screen. No refresh was triggered afterwards. 

CODE: I bind these events this way. Funny because on android it is still stable. Any ideas or is it possible to just fix how I initialize my wrapper?

$(document).on('pageinit', '#home', function () {   

```
        $(".iscroll-wrapper", this).bind({
            "iscroll_onpulldown" : function(){
                    app.refreshDataListing("");
            },
            "iscroll_onpullup"   : function(){
                    app.loadMoreData();
            }
        }); 
```

});

**Comment by harshgrovr** [comment]
did you find the solution?

**Comment by ecnopdev** [comment]
This issue is already out-dated and seems to have been resolved with the latest OS version. Thanks
