### ISSUE TITLE
Footer not showing

### ISSUE THREAD

**Issue by wilee88** [watusi/jquery-mobile-iscrollview#23]
Hello

Thank for the wonderful plugin.

I have a webapp on iPad2 iOS5, with a dynamically generated listview.
After filling the listview, i did a $("#content").iscrollview("refresh").
Everything works beautifully, the list has about 50 items, and scroll very nicely.

But I cannot get the footer to show.  (footer has navbar)
I tried data-position = "fixed", tried "inline", tried data-iscroll-fixed.

Is there anything you can think of that I'm not doing right?

Thank you very much.

**Comment by jtara** [comment]
Can you provide more details? (A scaled-down complete example is best.) Does the footer ever appear? Does it appear after your change orientation? Do you dynamically generate the entire listview, or just content inside the listview?

If you are dynamically generating the listview itself, you need to trigger "create" on the parent of the listview.

$("#listview-parent").trigger("create");

If you are dynamically changing content of the listview, make sure that you first refresh the listview itself. Do this before you refresh the iscrollview. 

$("#my-listview").listview("refresh");

Did you dynamically change anything outside of the listview? If so, you'll have to resize the wrapper.

$("#content").iscrollview("resizeWrapper");

**Comment by wilee88** [comment]
Hi Jon

Thank you very much for your email.

The listview was created in the body, and then the list is generated when
ready.

I was typing the codes to show you, and found out where I did wrong.  There
is an extra </div> before I put the footer.

Everything is working good now.

Thank you very much for your email, and your wonderful work.

Wilfred

-----Original Message-----
From: Jon Tara
[mailto:reply+i-5327258-70fd44a7c89d3014538dbe4f238daba933762359-1689762@rep
ly.github.com] 
Sent: Thursday, June 28, 2012 11:00 AM
To: wilee88
Subject: Re: [jquery-mobile-iscrollview] Footer not showing (#23)

Can you provide more details? (A scaled-down complete example is best.) Does
the footer ever appear? Does it appear after your change orientation? Do you
dynamically generate the entire listview, or just content inside the
listview?

If you are dynamically generating the listview itself, you need to trigger
"create" on the parent of the listview.

$("#listview-parent").trigger("create");

If you are dynamically changing content of the listview, make sure that you
first refresh the listview itself. Do this before you refresh the
iscrollview. 

$("#my-listview").listview("refresh");

Did you dynamically change anything outside of the listview? If so, you'll
have to resize the wrapper.

$("#content").iscrollview("resizeWrapper");

---

Reply to this email directly or view it on GitHub:

https://github.com/watusi/jquery-mobile-iscrollview/issues/23#issuecomment-6
636870
