### ISSUE TITLE
Scroller not created if there is no content inside wrapper

### ISSUE THREAD

**Issue by paulnorrie** [watusi/jquery-mobile-iscrollview#24]
Hi - I have a problem where the scrollbars are not being created

I have a page with an empty div with the attribute of data-iscroll.   On Jquery mobiles pageinit event, I make a $.ajax call and when that returns successfully, I add the response to this div and trigger a "create" to style it appropriately.   In the pageshow event, I call iscrollview refresh.  My content appears and is styled correctly but I get an error in the console indicating iscroll is null (so no refresh).

I'm not overly familiar with javascript but it seems that this is because iScroll has not created a scroller at this time because on the original page load, there was no need to (no content to scroll).   Therefore the iScroll object does not exist.

The solution to this is add at least some content in my otherwise empty div.  This allows iscroll to create a scroller object and the error goes away so I can refresh.  However the vertical scrollbar does not appear after the refresh.

Now this is because jquery-mobile.iscrollview has not created the scroller css classes in the div surrounding my new content added at the end of the ajax call.  jquery-mobile.iscrollview only does this in the _create method, which has been called before my ajax is loaded.   It seems I need a way to add these styles before my refresh method so iScroll knows the height of the scroller is > 0 and will render the scrollbar.

My HTML body is:

```
<div data-role="page" id="twocolumn">
    <div id="frame" data-iscroll>
           <p>This is here to make sure iScroll creates a scroller object otherwise we can never refresh</p>
    </div>
</div>
```

In the head is the script to load data:

```
<script type="text/javascript">
  $('#twocolumn).live('pageinit'), function(event){
     $.ajax({
        url:   'something/somewhere',
        type: 'GET',
       success: function(data) {
           $('#frame').html($(data)).trigger("create"); //inject html and enhance it
       }
     });
  });

$('#twocolumn).live('pageshow', function(event,ui){
    //want to tell iScroll that the height of the scroller is now changed and is > 0 
    //because otherwise it sees a height of 0 and will not create the scroller.

    //refresh scroll bar as our content in #twocolumn has likely changed height
    $('#frame').iscrollview("refresh", null, null, null, true);
});
</script>
```

 Any ideas on what to do?

Thanks heaps
Paul

**Comment by paulnorrie** [comment]
Not sure yet if this is a good idea but I'm just calling the _create method on it which sorts it out:

   $('#frame').iscrollview("_create")

**Comment by jtara** [comment]
That is a workaround, assuming you are calling it after you have added some content under the wrapper.

I'm going to mark this as a bug. I can see why this is happening. In `_createScroller`, I wrap `this.$wrapper.children()` with a `<div>`. But, of course, if there are no children, there is nothing to wrap, and the `<div>` is never created. I'll have it test for that and go ahead and create an empty `<div>` in that case.

Bear in mind, though, that if you populate the content after the widget has been created, then `#frame` is _not_ the place to put it! You will need to put it in the `iscroll-content` div which the plugin has created. `$("#frame .iscroll-content"). I'll add something to the documentation about inserting dynamic content.

**Comment by jtara** [comment]
Fixed in commit 7ecae44f4b

You can now simply add `iscroll-wrapper` to some element and not create any content under that element. An empty content `<div>` will be created for you in this case.

If you are adding dynamic content, make sure to add it inside the `iscroll-content` div that is created for you, _not_ the wrapper. Then call `create()` on the `iscroll-content` div to enhance your added elements before calling `.refresh()` on the wrapper.

Note that a scrollbar will not appear unless content is taller than the wrapper. (A scrollbar appears when you have short content with a pull-down or pull-up, because the content is then, in fact (including the pull-down or pull-up) taller than the wrapper.) This is behavior of iscroll.js itself.

**Comment by paulnorrie** [comment]
Great stuff - thanks Jon.  It's a nice library you've created.

**Comment by play75010** [comment]
Hello. Where can I find an example of adding dynamic content ? 

I'm not sure I understand "add it inside the iscroll-content"

Thank you
