### ISSUE TITLE
How to use with fixed positioning

### ISSUE THREAD

**Issue by genXdev** [watusi/jquery-mobile-iscrollview#33]
Hi there,

First of all, very nice widget!

I just want to report a problem I am having with it, in my project.

My jQuery mobile project uses generated style sheets with lots of media queries to position my Header, Footer AND sidebars using fixed positioning.

My scrollable areas work initialiy, but after a resize or orientation change they simply don't get updated, they are not aware of the increase or decrease of visible area.

I tried almost all of the settings, even manually calling update and resizeWrapper, but I am getting the feeling it was not build with fixed positioning and side-bars in mind.

Is there a workarround I could use to make them update manually or could this be fixed?

Keep up the good work!!

cheers,

René

**Comment by jtara** [comment]
In this case, you probably should fixed-position the wrapper itself, and do any resizing of the wrapper yourself. Disable the `resizeWrapper` option.

The defaults are meant to make it very easy to handle the most common case of a fixed header and fixed footer (emulated using inline) with scrolling content in-between. Anything else, and you need to set some options and take control of positioning and sizing of the wrapper.

**Comment by genXdev** [comment]
Hi..

I did what you say, disabled the resizeWrapper option, checked if the .iscroll-wrapper element is sized appropriately, and it is, all done by stylesheets.

I then continued to inspect the DOM elements with chrome's Developper Tools, and noticed that  the .iscroll-scroller element (inside the wrapper) was not (re)sized, so I added the following lines to the stylesheet:

/\* The scroller is the element that contains the elements that are scrolled. The height of this
- element is typically longer than the wrapper. (It's the stuff that we scroll.) The widget
- creates this element for you. It wraps all of the children of the wrapper.
  */

.iscroll-scroller {
  /\* Add any styles that you want to add to scrollers */
  position:inherit;
  left:inherit;
  top:inherit;
  bottom:inherit;
  right:inherit;  
}

Now the (real?) wrapper with the class .iscroll-scroller has the right position, even after a resize.

But guess what?  Now the scroller isn't scrolling anymore, it stays fixed, even though the .iscroll-content element is like three times the height of this .iscroll-scroller parent..

Any ideas?

**Comment by genXdev** [comment]
Reading the comment of the CSS header above, I realize I did size the wronge one.

But then.. the .scroll-wrapper  was already resized automatically by CSS  using position:fixed,  top, left, right, bottom.

But it didn't work.. even with resizeWrapper being false..

**Comment by genXdev** [comment]
I fixed it.. :)

a simple:

$(window).resize(function () {
    $('.iscroll-content:visible').trigger('updatelayout');
});

solved the problem..

Thanks anyway..
