### ISSUE TITLE
Problems with image scrolling

### ISSUE THREAD

**Issue by droidpl** [watusi/jquery-mobile-iscrollview#37]
When I include an image into an scrollable content, this image is not taken into account for the size of the scroll. This only happends the first time the page is loaded, because one it's cached it seems to work correctly. This is the code I have used to test it:

[HTML] 
<code>
&lt;div data-iscroll data-role="content">
   &lt;img id="main_poi_image" src="./img/image1.png"/&gt;
   &lt;img="main_poi_image" src="./img/image2.png"/&gt;
   &lt;img id="main_poi_image" src="./img/image3.png"/&gt;
   &lt;img id="main_poi_image" src="./img/image4.png"/&gt;
&lt;/div&gt;
</code>
[/HTML]

The images are correctly displayed but when it goes out of the display I can't scroll on them on y-axis. Confirm me this is a bug or tell me how to solve it.
My real program has images with texts and lists on the same page, and this problem on not detecting images makes the page to be scrollable only as it has not images and cuts some of my text content.
The navigator I'm using is Safari for iPhone on iOS 5.

If you need more feedback, tell me. Thanks.

**Comment by droidpl** [comment]
Ok, this was related to a delay on the image loading. It was solved by using the delay (500ms) on refresh() call. Thanks

**Comment by willyue** [comment]
@Feantury  hi, im facing the same problem with you. Can you describe more on how you solved it? 
Million thanks~~~~~
