### ISSUE TITLE
Ack! github killed all my issues! Everybody please read!

### ISSUE THREAD

**Issue by jtara** [watusi/jquery-mobile-iscrollview#38]
Great. github update apparently removed all my issues except for one. Thanks, github. ;(

It shows 12 issues, but there were way more than that. And then it only shows one open issue, and no closed.

If you had an issue, and don't see it here, please wait until I check with GitHub and post an update here. If they can't get my issues back, you will have to enter them again. But wait until I post an update, so we don't get everything messed-up.

**Comment by jtara** [comment]
OK, filters are to blame. I could swear I didn't click on any filters...

Ignore.

**Comment by destroy** [comment]
lol
