### ISSUE TITLE
Doesn't work with jqm 1.2.0 alpha 1

### ISSUE THREAD

**Issue by szanata** [watusi/jquery-mobile-iscrollview#43]
I know this jqm version (1.2.0 alpha 1) is under development, but I tested it with this plugin and doesn't worked. I got an execution error: "cannot call .split of undefined".

I'm developing using iscrollview with jqm 1.1.1 and works great. Thanks for your effort!

**Comment by jtara** [comment]
I have also been testing now with JQM 1.2beta, with no problems.

Please report any specific issues you with with JQM 1.2 along with an example.

Thanks.

**Comment by jtara** [comment]
Could you please test with version 1.2.5 and let me know if you still have issues?

Thanks.

**Comment by szanata** [comment]
I tested with jqm 1.2 beta 1 and it worked perfectly. Soon, I will test with RC and report any issue!

Thanks again!

**Comment by jtara** [comment]
Reported fixed in version 1.2.5
