### ISSUE TITLE
iScrollView Disable the page scroll

### ISSUE THREAD

**Issue by FlyersWeb** [watusi/jquery-mobile-iscrollview#44]
I got a multipage with two pages with two scrolls

The scroll for the two elements is fine but I can't scroll down from outside those elements.

**Comment by jtara** [comment]
I'm afraid I don't understand you question.

Can you re-phrase or upload an image to illustrate?

**Comment by jtara** [comment]
The widget normally disables scrolling of the page itself, as this is normally desirable.

If you want to allow scrolling of the page, you can set the `preventPageScroll` option to `false`.
