### ISSUE TITLE
Problem with jQuery mobile Slider 

### ISSUE THREAD

**Issue by genXdev** [watusi/jquery-mobile-iscrollview#45]
Hi.

If I have a set of  (jQM) Slider controls inside a scrollable region, it seems that the left mouse button seem "stuck" after changing a slider from on to off or from off to on. This causes the page to scroll on every mouse move afterwards.

Does anyone have a workaround?

**Comment by Hexodus** [comment]
Same problem here. Using the range slider causes the page to scroll away. Took a while to realize what happens. Is it possible to disable certain elements? I need badly a solution.
This seems to happen only on Android 2.x devices. My Nexus is ok.
