### ISSUE TITLE
Incorrect expression in _calculateBarsHeight - causes "Syntax error, unrecognized expression" error

### ISSUE THREAD

**Issue by mseelye** [watusi/jquery-mobile-iscrollview#46]
One about line 1032 of the iscrollview js in the "_calculateBarsHeight" function there is an if statement that looks like:

if (id === "" || !$barsInPage.is(":jqmData(id='" + id + "')'")) {

I believe it should be:

if (id === "" || !$barsInPage.is(":jqmData(id='" + id + "')")) {

(Note the removed extra ' character.)

With jQuery 1.8.1 and JQM 1.2 beta this was causing me to get errors that looked like: 
   Syntax error, unrecognized expression: [data-id='someFooterDataId']'  

(note the ' at the end of the error message)

In any case, for whatever reason, I don't get these errors with 1.7.1 and JQM 1.1.1 - however I need to upgrade to fix unrelated issues.

**Comment by jtara** [comment]
Nice catch!

Both jslint and jshint missed this...

**Comment by jtara** [comment]
Fixed in commit c6cdc77d

**Comment by jtara** [comment]
Pushed to github.
