### ISSUE TITLE
Scrolling not working on Android 2.3.3

### ISSUE THREAD

**Issue by superoelk** [watusi/jquery-mobile-iscrollview#50]
Hi there,

I am recently using iscrollview to build mobile apps and my primary experience is great.
On my Galaxy Tab 2 it works without problems!

But on my Galaxy S running Android 2.3.3 it does not scroll. In one of ten tries it scrolls, in the other cases it doesn't do anything.
The sample app I'm using to test it shows a simple listview of hyperlinks, so nothing special.
I am running the recent version of iscrollview, jquery 1.6.4 and jquery mobile 1.0.1
Is there any fix for this, maybe it's a configurational thing about the buttons..?

Thanks!

UPDATE:
I tried the original demo of iscrollview.
Galaxy S is working quite okay on 1.1.1 (1.0.1 still doesn't work), Galaxy Tab 2 is flickering like hell... So now it works on my smartphone, but not on my tablet anymore.
Does anyone understand this?

**Comment by superoelk** [comment]
Well, I figured it out.

@media DISABLED { 
  .iscroll-scroller, 
  .iscroll-scroller \* {
    -webkit-transform: translateZ(0);
  }
}

/\* So, for the demo, I'm using this one, which doesn't target the scroller itself, and
   targets specific top-level elements inside the scroller. */
@media all { 
  .iscroll-content li  {
    -webkit-transform: translateZ(0);
  }
}

This part is supposed to be speeding the whole thing up, but it causes my Galaxy Tab 2 to flicker extremely.
Furthermore, JQuery 1.0.1 is killing iScroll on my Galaxy S.

**Comment by jtara** [comment]
The`translateZ(0)` hack is not needed for Android, but is necessary for performance on all versions of Safari. (not Webkit in general - just Safari.)

I will update the demo so that it only applies that CSS hack for Safari.

**Comment by superoelk** [comment]
Hey Jon,

thanks for your quick response.
Okay, good to know that it's for Safari.
I'm looking forward to seeing your modified demo.

Great job you did creating iscrollview!
