### ISSUE TITLE
2nd pull-down: Arrow doesn't stop rotating

### ISSUE THREAD

**Issue by atuttle** [watusi/jquery-mobile-iscrollview#58]
Using PhoneGap 2.1.0, jQuery 1.8.2, jQuery Mobile 1.2

```
<div data-role="page" id="people">
    <div data-role="header">
        <a href="#home">Home</a>
        <h1>People</h1>
    </div>
    <div data-role="content" data-iscroll>
        <ul id="peopleContent"></ul>
    </div>
</div>
```

The first time I pull down it works as expected. If I complete the pull-to-refresh action, then pull down again, the arrow is continuously rotating in a complete circle. Tested on both an iPod Touch (iOS 6.0.1) and Galaxy Nexus (Android 4.1.1), and it happens on both. Does not happen in the browser on my laptop.

**Comment by digaoddc** [comment]
This is also happening to me(on pull down). The arrow keeps rotating, only works fine on the first time.
Tested on IOS 6.0. 
I`m using Phonegap 2.1, jQuery 1.8.2 and jQuery Mobile 1.2

**Comment by atuttle** [comment]
I've got it fixed for android, and am working on iOS. Hope to send a pull request today.

**Comment by atuttle** [comment]
https://github.com/watusi/jquery-mobile-iscrollview/pull/59

**Comment by jtara** [comment]
Thanks for the pull request. Just need to look into why you are replacing the icon element.

**Comment by atuttle** [comment]
That was the only way I could get it to stop rotating. Unfortunately this makes it "snap" into place instead of rotating into place, but I figured that was the lesser of the two evils.
