### ISSUE TITLE
Cannot call methods on iscrollview prior to initialization

### ISSUE THREAD

**Issue by wbramw** [watusi/jquery-mobile-iscrollview#61]
On my current project, I need to add the 'data-iscroll' attribute in JS code after the page is loaded. When I do this, nothing really changes in the browser and I still see the original (ugly) scrollbar of the browser. So I tried to call the refresh method of iscrollview, but then i get the following error in the Chrome console: "Uncaught Error: cannot call methods on iscrollview prior to initialization; attempted to call method 'refresh' ".
The code to achieve this is fairly simple:

$(document).ready(function(){
     $("[data-role='content']").attr("data-iscroll",""); //adds the data-iscroll attribute to the content div
     $("[data-iscroll"].iscrollview("refresh"); // refresh --> fails
});

**Comment by atuttle** [comment]
Try this:

```
$(document).ready(function(){
    $("[data-role='content']").attr("data-iscroll",""); //adds the data-iscroll attribute to the content div
    $("[data-iscroll]").iscrollview();
});
```

The widget is trying to initialize before you're adding the `data-iscroll` attribute, so it's not finding anything to initialize. If I'm reading the source correctly, my example should cause it to initialize after you add the attribute.

**Comment by jtara** [comment]
Yes, the automatic initialization only works if the `data-iscroll` property is found when the `pagecreate` event is sent. If you add the property later, then you need to instantiate the widget yourself.

You shouldn't be using  `$(document).ready`, though. See:

http://jquerymobile.com/demos/1.2.0/docs/api/events.html

Big yellow box, top of the page.

**Comment by sureshpattu** [comment]
@wbramw Hi I also faced the same problem then I changed my code to following one then works fine for me :) 
Try this
$(document).ready(function(){
$("[data-role='content']").attr("data-iscroll",""); //adds the data-iscroll attribute to the content div
$("[data-iscroll"].iscrollview(); // First create iscrollview
$("[data-iscroll"].iscrollview("refresh"); // now refresh the iscrollview
});
