### ISSUE TITLE
Does the data object passed to event listeners contain a reference to a single central instance of iscrollview, or some copy or instance specific to that scroller/page?

### ISSUE THREAD

**Issue by atuttle** [watusi/jquery-mobile-iscrollview#65]
https://github.com/watusi/jquery-mobile-iscrollview#bound-callback-parameters

Event listeners are passed the event object and the data object (e.g. `data.iscrollview` and everything in it)...

Is this data object a singleton or a transient object, or somewhere in between? Or put another way, if I add a property to data.iscrollview on one page, is that property going to be available on another?

I'm asking because I'm implementing infinite scrolling and would like to attach a few properties to it to indicate states/etc, and I don't want to pollute other pages or cause unexpected behavior on them.

Thanks!

**Comment by jtara** [comment]
Each scroller instantiates a separate object. It has nothing to do with pages, since you can have multiple scrollers on a page.
