### ISSUE TITLE
How to set the createScroller value

### ISSUE THREAD

**Issue by wbramw** [watusi/jquery-mobile-iscrollview#68]
How can you set the createScroller value for a div that should be scrolled?

Right now I'm using data-iscroll="{'createScroller':false}" as attribute on the div but this is not working, the content is still wrapped in an extra (unwanted) div.

**Comment by jtara** [comment]
`data-iscroll="{'createScroller':false}"`is not valid JSON. Reverse your quotes:

`data-iscroll='{"createScroller"::false}'`

JSON requires double-quotes.
