### ISSUE TITLE
Scroll bar shows on right side of the screen rather than the DIV

### ISSUE THREAD

**Issue by fuping** [watusi/jquery-mobile-iscrollview#7]
I have a tablet app with a split view, which a list on the left hand side and content on the right.
I added 'data-iscroll' on the list's div,
but the scroll bar showed on the right side of the whole screen rather than the div with 'data-iscroll'.
It works expect this display issue.

Or did I miss anything?

There is a workaround which hides the scroll bar:
set vScrollbar: false,  in options

**Comment by jtara** [comment]
Yes, that's how iScroll4 works, unfortunately. You will need to customize your scrollbar per the iScroll4 documentation.

You will need to set the scrollbarClass option, and provide CSS to place and style the scrollbar.

See http://cubiq.org/iscroll-4, page-down to "custom scrollbars".

**Comment by jtara** [comment]
This was a bug in iscrollview. iScroll does not normally create full screen-height scroll bars. They are now created the height of the wrapper.
