### ISSUE TITLE
scroll dose not take image height into calculation.

### ISSUE THREAD

**Issue by aisliuyifei** [watusi/jquery-mobile-iscrollview#71]
When I include an image into an scrollable content, this image is not taken into account for the size of the scroll. It only happens the first time the page is loaded,once it's cached it just worked fine. 

I know exactly someone else posted the same question 6 months ago, I tried his solution, add this:
    setTimeout(' $(".iscroll-wrapper").iscrollview("refresh");',1000);
but still not working.
many thanks if any help

**Comment by lpfister** [comment]
Hello,

That is normal, u need to put a height to the image or refresh once loaded

**Comment by aisliuyifei** [comment]
3ks for your reply, tested adding height attribute to image tag, yes ,the problem solved.
but I need the image to fit the width of screen width like this width='"100%",  and the height should not be set as an constant.

**Comment by aisliuyifei** [comment]
I calculated image height first and set the height as float value to image tag , problem solved,but not satisfied, maybe sometime later ,I can find a much better way out
