### ISSUE TITLE
How to disable rubber band bounce effect using jquery.mobile.scrollview

### ISSUE THREAD

**Issue by PrashanthBhat** [watusi/jquery-mobile-iscrollview#77]
I am using jquery.mobile.scrollview in my phonegap application. I want to disable the scrolling rubber band bounce effect. Can this be disabled ?

**Comment by jtara** [comment]
Yes. You can set the `bounce` option to `false`.

I don't document iScroll options - just options added by `iscrollview`. You need to check with the iScroll documentation for internal iScroll options. All iScroll options can be set via any of the iscrollview options-setting mechanisms.

**Comment by Saporules** [comment]
where do I can find and change the bounce option?

**Comment by jvjvjv** [comment]
If you need help finding and changing the bounce option, please turn to the original developer.

http://cubiq.org/iscroll-4

**Comment by jtara** [comment]
There's nothing to find. The `bounce` option is called `bounce`.
