### ISSUE TITLE
Scrolling problem after innerHTML update of a DIV

### ISSUE THREAD

**Issue by xpinternetsolutions** [watusi/jquery-mobile-iscrollview#79]
Hi guys, I desperately need assistance. I've been trying to get my code work for about 1,5 day but no effect.
Problem is that de scrollbars dispappear after a innertHTML update of a DIV.
I have tried everything I could think of and read about in forums, documents etc.. like destroy, refresh.
Nothing worked so far.

Help will be appreciated!!!
 &lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
&lt;title&gt;&lt;/title&gt;
&lt;meta http-equiv="Content-type" content="text/html; charset=utf-8"&gt;

&lt;meta name="apple-mobile-web-app-capable" content="yes" /&gt;
&lt;meta name="apple-mobile-web-app-status-bar-style" content="black"&gt;
&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;

&lt;style type="text/css"&gt;
/\* Prevent copy paste for all elements except text fields */
-  { -webkit-user-select:none; -webkit-tap-highlight-color:rgba(255, 255, 255, 0); }
  input, textarea  { -webkit-user-select:text; }
  &lt;/style&gt;

&lt;link rel="stylesheet" href="http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.css" /&gt;
&lt;link rel="stylesheet" href="http://www.ezy-booking.com//artists/shopping/apps/venues/jquery-mobile-iscrollview-master/lib/jquery.mobile.iscrollview.css" /&gt;
&lt;link rel="stylesheet" href="http://www.ezy-booking.com//artists/shopping/apps/venues/css/animate.css-master/animate-custom.css" /&gt;

&lt;script src="http://code.jquery.com/jquery-1.8.2.min.js"&gt;&lt;/script&gt;
&lt;script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"&gt;&lt;/script&gt;
&lt;script src="http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.js"&gt;&lt;/script&gt;

&lt;script type="text/javascript" charset="utf-8" src="http://www.ezy-booking.com/artists/shopping/apps/venues/cubiq-iscroll-d31d6e6/src/iscroll.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" charset="utf-8" src="http://www.ezy-booking.com/artists/shopping/apps/venues/javascript-jquery.mobile.iscroll-master/jquery.mobile.iscroll.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" charset="utf-8" src="http://www.ezy-booking.com/artists/shopping/apps/venues/jquery-mobile-iscrollview-master/lib/jquery.mobile.iscrollview.js"&gt;&lt;/script&gt;

&lt;script type="text/javascript" charset="utf-8" src="http://www.ezy-booking.com/artists/shopping/apps/venues/js/appmobi_local_bootstrap.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" charset="utf-8" src="http://www.ezy-booking.com/artists/shopping/apps/venues/js/xhr.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" charset="utf-8" src="http://www.ezy-booking.com/artists/shopping/apps/venues/js/jquery.xdomainajax.js"&gt;&lt;/script&gt;

&lt;script type="text/javascript" charset="utf-8" src="//cdn.app-framework-software.intel.com/jq.ui.min.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" charset="utf-8" src="//cdn.app-framework-software.intel.com/jq.mobi.min.js"&gt;&lt;/script&gt;

&lt;script type="text/javascript"&gt;
/\* This function runs once the page is loaded, but appMobi is not yet active */
var init = function(){
    // ajaxEnabled=true;
    // allowCrossDomainPages=true;
    // $('#main').addClass('animated fadeInRightBig');
    // $('#menuleft').addClass('animated fadeIn');
};

window.addEventListener("load",init,false);

var preventDefaultScroll = function(event) {
   event.preventDefault();
   window.scroll(0,0);
   return false;
};
document.addEventListener('touchmove', preventDefaultScroll, false);

var onDeviceReady=function(){
    AppMobi.display.useViewport(768,1024);
    AppMobi.device.hideSplashScreen();
    AppMobi.device.getRemoteData('http://www.ezy-booking.com/artists/shopping/apps/venues/app_show_event_genrelist.cgi',"GET","E-MAIL=support@appmobi.com&TEST=1&MAX=0","success_handler_getMenuData","error_handler_getMenuData");
}

document.addEventListener("appMobi.device.ready",onDeviceReady,false);
&lt;/script&gt;

&lt;script type="text/javascript"&gt;
function getMenuData(url) {
     AppMobi.device.getRemoteData(url,"GET","","success_handler_getMenuData","error_handler_getMenuData");
}

function success_handler_getMenuData(data) {
    document.getElementById('menuleft').innerHTML=data;
    $(".menuClass").iscrollview("refresh");
}

function error_handler_getMenuData(data) {
    alert('An error occurred.\nPlease try again.');
}

function getBodyData(url) {
        AppMobi.device.getRemoteData(url,"GET","","success_handler_getBodyData","error_handler_getBodyData");
}

function success_handler_getBodyData(data) {
    document.getElementById('main').innerHTML=data;
    $(".mainClass").iscrollview("refresh");
}

function error_handler_getBodyData(data) {
    alert('An error occurred.\nPlease try again.');
}

&lt;/script&gt;
&lt;/head&gt;

&lt;body&gt;
&lt;div id="jQUi" data-role="page"&gt;

&lt;div data-role="header" id="header" data-tap-toggle="false" data-position="fixed" style="position:fixed !important;top:0px;left:0px !important;width:100%;height:50px;background-color:#ffffff;overflow:none"&gt;
&lt;h1&gt;EZY-Booking | Where Entertainment Goes Live&lt;/H1&gt;
&lt;a href="#" data-icon="check" data-theme="a" class="ui-btn-right"&gt;&lt;span style="color:#ffffff"&gt;Join us&lt;/span&gt;&lt;/h1&gt;&lt;/a&gt;
&lt;div data-role="navbar" data-tap-toggle="false style="background-color:#434343"&gt;
&lt;ul&gt;
&lt;li&gt;&lt;a href="javascript:getMenuData('http://www.ezy-booking.com/artists/shopping/apps/venues/app_show_event_occasionlist.cgi');"&gt;Ocasion&lt;/a&gt;
&lt;li&gt;&lt;a href="javascript:getMenuData('http://www.ezy-booking.com/artists/shopping/apps/venues/app_show_event_categorylist.cgi');"&gt;Category&lt;/a&gt;
&lt;li&gt;&lt;a href="javascript:getMenuData('http://www.ezy-booking.com/artists/shopping/apps/venues/app_show_event_genrelist.cgi');"&gt;Genre&lt;/a&gt;
&lt;li&gt;&lt;a href="javascript:getMenuData('http://www.ezy-booking.com/artists/shopping/apps/venues/app_show_event_formationlist.cgi');"&gt;Formation&lt;/a&gt;
&lt;/ul&gt;
&lt;/div&gt;
&lt;/div&gt;

&lt;div id="content" data-role="content"&gt;

&lt;div id="subnav" style="position:fixed;top:70px;left:0px;width:191px;bottom:38px;height:100%;background-color:#434343;border:1px solid #000000"&gt;
&lt;!-- &lt;img src="http://www.ezy-booking.com/img/logo/logo.png" style="width:191;height:137px" id="logo"&gt; --&gt;
&lt;div id="menuleft" class="menuClass" data-iscroll="enable" style="position:absolute;overflow:auto;bottom:38px;top:200px;left:0px;width:191px;background-color:#434343"&gt;
&lt;div id="wrapperMenu"&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;

&lt;div id="main" class="mainClass" data-iscroll="enable" title="" selected="true" style="position:absolute;overflow:auto;bottom:50px;top:238px;left:200px;background-color:#eaeaea;color:#333333"&gt;
&lt;div id="wrapperMain"&gt;
MAIN: Cohen: grote fouten bij rellen Haren
&lt;br&gt;&lt;br&gt;
Zowel de politie van Groningen als burgemeester Rob Bats van Haren hebben grote fouten gemaakt bij de Facebookrellen in het Groningse villadorp vorig jaar. Dat concludeert de commissie die onder leiding van Job Cohen onderzoek deed naar de ernstige ongeregeldheden. De belangrijkste conclusies van het rapport zijn uitgelekt en die liegen er niet om.
&lt;br&gt;&lt;br&gt;
Weekendabonnement&lt;br&gt;
Proefabonnement,&lt;br&gt;
10 weken € 30,-!&lt;br&gt;
Ads door Google&lt;br&gt;
WOW Slider Coupon Code&lt;br&gt;
&lt;br&gt;&lt;br&gt;
Liked Free WOW Slider? Buy Full Version Now and Save Big!
&lt;br&gt;&lt;br&gt;
&lt;a href="AppMobi.device.launchExternal('http://www.google.com');"&gt;site&lt;/a&gt;
&lt;br&gt;
&lt;a href="http://www.ezy-go.com" rel="external" data-ajax="false"&gt;WOWSlider.com&lt;/a&gt;
&lt;br&gt;&lt;br&gt;
Wonen in Duitsland
&lt;br&gt;&lt;br&gt;
Informatie over o.a. belasting, sociale zekerheid en ziektekosten.
&lt;br&gt;&lt;br&gt;
www.GrensinfoPunt.nl
&lt;br&gt;&lt;br&gt;
GOGO Kos Stad 2013
&lt;br&gt;
Goedkoop feesten & chillen? Kos Stad is het helemaal!
&lt;br&gt;
Kos-Stad.GOGO.nl
&lt;br&gt;
Agenten waren slecht voorbereid en de burgemeester heeft te lang gewacht met het inroepen van hulp. Ook waren er te weinig leden van de Mobiele Eenheid, die bovendien veel te laat ter plaatse waren. De politie begreep ook nog eens niets van sociale media.
&lt;br&gt;&lt;br&gt;
De Facebookrellen ontstonden toen duizenden jongeren zich op 21 september in Haren verzamelden voor het verjaardagsfeestje van het 15-jarige meisje Merthe. De uitnodiging voor het feest was per ongeluk bij tienduizenden gebruikers van Facebook terechtgekomen. Het kwam tot ernstige rellen in het Groningse dorp, waarbij de relschoppers onder meer lantaarnpalen, verkeersborden en auto's vernielden. Het Verbond van Verzekeraars schat de totale schade op ongeveer 1 miljoen euro.
&lt;br&gt;&lt;br&gt;
Zover had het allemaal niet hoeven komen, concludeert Cohen. De voorbereiding was echter flink onder de maat. Maar ook toen het eenmaal uit de hand was gelopen, traden de autoriteiten niet adequaat op. Agenten slaagden er bijvoorbeeld niet in om contact te krijgen met leidinggevenden en de Mobiele Eenheid was veel te laat ter plaatse. Dat is deels de schuld van burgemeester Bats. Die heeft te lang gewacht met het opschalen van de crisisorganisatie, waardoor ME'ers van andere korpsen pas kwamen toen de rellen al in volle gang waren.
&lt;br&gt;&lt;br&gt;
Volgens de commissie was de speelruimte van de politie aan een kant beperkt door de besluiten van politie, jusitie en burgemeester. Die wilden een normale gang van zaken, Haren niet afsluiten en zo weinig mogelijk zichtbare politie. Dat pakte desastreus uit.
&lt;br&gt;&lt;br&gt;
Job Cohen presenteert het rapport morgen officieel op een persconferentie in het gemeentehuis van Haren.
&lt;/div&gt;
&lt;/div&gt;

&lt;div data-role="footer" data-tap-toggle="false" data-position="fixed" style="position:fixed !important;left: 0px !important;right: 0px !important;bottom: 0px !important;z-index: 999 !important;"&gt;
&lt;div data-role="navbar"&gt;
&lt;ul&gt;
&lt;li&gt;&lt;a href="javascript:AppMobi.device.launchExternal('http://www.ezy-booking.com');"&gt;Organization&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="javascript:AppMobi.device.launchExternal('http://www.facebook.com');"&gt;Facebook&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="#"&gt;Twitter&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="#"&gt;Pinterest&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="javascript:getExternalData('http://www.ezy-booking.com/artists/shopping/apps/venues/app_show_event_occasionlist.cgi');"&gt;Website&lt;/a&gt;
&lt;/ul&gt;
&lt;/div&gt;
&lt;/div&gt;

&lt;/div&gt;
&lt;/body&gt;
&lt;/html&gt;

Regards,
Henk

**Comment by jtara** [comment]
Wow, you're mixing a whole BUNCH of incompatible stuff, and I wouldn't have any expectation for this to work.

jQuery Mobile and jQuery UI are a known incompatibility. They weren't desired to be compatible at all, even though they are both published by jQuery Foundation. Some people have managed to get parts of them to work together, but it gets more difficult with each new version released of each.

And then you load jq.mobi as well, which as far as I know is meant as a "competitor" for jQuery Mobile.

jquery.mobile.iscrollview wasn't meant to be compatible with either jQuery UI nor jq.mobi.
