### ISSUE TITLE
demo page not working

### ISSUE THREAD

**Issue by thenibbana** [watusi/jquery-mobile-iscrollview#90]
demo build page form.html not working properly. Form element is not shown in full page

**Comment by jtara** [comment]
I don't understand what you mean by "form element is not shown in full page". Can you upload a screenshot? What browser(s)?

Forms are not usable on iOS, due to interference from Mobile Safari Forms Assistant. This is a long-standing issue with all iScroll implementation.

**Comment by thenibbana** [comment]
![Untitled](https://f.cloud.github.com/assets/1822685/407548/49af4d26-aaff-11e2-86d9-69bf436ceaf0.png)
the <li> element are not shown in full screen width.
mozilla firefox v21.0;

Also page has to be refreshed while navigating to different page using jqm & requireJS
